### ISSUE TITLE
Installing for MAC

### ISSUE THREAD

**Issue by kelliconlin** [boundlessgeo/qgis-mgrs-tools-plugin#4]
I am new user of QGIS and I am trying to install the plugin on MAC and the plugin shows as unavailable. 
I downloaded the file and unzipped and added the URL. Is there specific instructions for loading on MAC? 

Im using QGIS 8.14

**Comment by luipir** [comment]
for this plugin, you should copy or create a sym link: e.g
cp -r <where you downloaded>/qgis-mgrs-tools-plugin/mgrstools
        <your home>/.qgis2/python/plugins/mgrstools

**Comment by luipir** [comment]
if it fix your installation problem... please close the issue

thank you

**Comment by kelliconlin** [comment]
Thank you!
