### ISSUE TITLE
This plugin is broken - wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by tsteles473** [boundlessgeo/qgis-mgrs-tools-plugin#6]
Hi.
I installed the mgrs-tools by the Boundless plugin repository, but now i get this error:

> This plugin is broken
> /home/tsteles/.qgis2/python/plugins/mgrstools/ext-libs/mgrs/libmgrs.so: wrong ELF class: ELFCLASS64
> 

My ubuntu is 32 bit version (i686 GNU/Linux).
Any help? Thanks

**Comment by alexbruy** [comment]
New version of plugin now does not need binaries.
