### ISSUE TITLE
The MGRS processing provider is not showing on QGIS 3.2

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-mgrs-tools-plugin#9]

**Comment by SrNetoChan** [comment]
The documentation and testa also don't make any reference to the MGRS provider for processing. So I wonder if this was not working on QGIS 2.18 already.

**Comment by SrNetoChan** [comment]
I was not sure that it worked before on qgis 2.x versions, so I confirmed:

![image](https://user-images.githubusercontent.com/3607161/43270584-558cf77c-90ed-11e8-8f41-5471b172ead3.png)

I should add documentation about these tools no the plugin documentation.

**Comment by volaya** [comment]
fixed
